export const INDIAN_STATES =  [ "Andhra Pradesh",
"Arunachal Pradesh",
"Assam",
"Bihar",
"Chhattisgarh",
"Goa",
"Gujarat",
"Haryana",
"Himachal Pradesh",
"Jharkhand",
"Karnataka",
"Kerala",
"Madhya Pradesh",
"Maharashtra",
"Manipur",
"Meghalaya",
"Mizoram",
"Nagaland",
"Odisha",
"Punjab",
"Rajasthan",
"Sikkim",
"Tamil Nadu",
"Telangana",
"Tripura",
"Uttarakhand",
"Uttar Pradesh",
"West Bengal",
"Andaman and Nicobar Islands",
"Chandigarh",
"Dadra and Nagar Haveli",
"Daman and Diu",
"Delhi",
"Jammu and Kashmir",
"Ladakh",
"Lakshadweep",
"Puducherry"];

export const EMPTY_FIELD_ERROR = 'Please fill out this field',
PWORD_ERROR = 'Please enter a password with atleast 8 characters',
EMAIL_ERROR = 'Please enter a valid email id',
FNAME_ERROR = 'Please enter your first name',
LNAME_ERROR = 'Please enter your last name', 
MOBILE_ERROR = 'Please enter 10-digit mobile number';